name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y doxygen
        && sudo apt-get install -y sphinx-doc
        && pip install sphinx-rtd-theme
        && pip install breathe
        && pip install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run: cd doc
        && make html
        && cd _build/html
        && touch .nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: doc/_build/html
